### ISSUE TITLE
Version check failure causing large log messages

### ISSUE THREAD

**Issue by DocterDum** [refinedmods/refinedstorageaddons#86]
### Describe the bug

When launching with RS Addons installed, it tries to connect to download an update JSON file and fails (https://refinedmods.com/refined-storage-addons/update.json)

### How can we reproduce this bug or crash?

1. Install RS
2. Install RS Addons
3. Launch Game

### What Minecraft version is this happening on?

Minecraft 1.16.5

### What Forge version is this happening on?

36.2.26

### What Refined Storage Addons version is this happening on?

0.7.4

### Relevant log output

```shell
[12:16:21] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [refinedstorageaddons] Starting version check at https://refinedmods.com/refined-storage-addons/update.json
[12:16:21] [Forge Version Check/WARN] [ne.mi.fm.VersionChecker/]: Failed to process update information
java.io.FileNotFoundException: https://refinedmods.com/refined-storage-addons/update.json
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_322] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_322] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_322] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_322] {}
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1952) ~[?:1.8.0_322] {}
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1947) ~[?:1.8.0_322] {}
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_322] {}
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1946) ~[?:1.8.0_322] {}
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1516) ~[?:1.8.0_322] {}
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1500) ~[?:1.8.0_322] {}
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268) ~[?:1.8.0_322] {}
	at net.minecraftforge.fml.VersionChecker$1.openUrlStream(VersionChecker.java:171) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.VersionChecker$1.process(VersionChecker.java:187) ~[forge:?] {re:classloading}
	at java.lang.Iterable.forEach(Iterable.java:75) [?:1.8.0_322] {}
	at net.minecraftforge.fml.VersionChecker$1.run(VersionChecker.java:139) [forge:?] {re:classloading}
Caused by: java.io.FileNotFoundException: https://refinedmods.com/refined-storage-addons/update.json
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1898) ~[?:1.8.0_322] {}
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1500) ~[?:1.8.0_322] {}
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[?:1.8.0_322] {}
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:352) ~[?:1.8.0_322] {}
	at net.minecraftforge.fml.VersionChecker$1.openUrlStream(VersionChecker.java:155) ~[forge:?] {re:classloading}
	... 3 more
```

**Comment by raoulvdberge** [comment]
Yes, not much I can do about that.
